update crest and bin/crest_edger

diff --git a/bin/crest b/bin/crest
--- a/bin/crest
+++ b/bin/crest
@@ -14,25 +14,27 @@ cat << EOF
 Program: crest (CREST-seq analysis pipeline Ren Lab)
 Version: v06.26.2016
 Contact: Rongxin Fang <r3fang@ucsd.edu>
-Ren Lab: http://bioinformatics-renlab.ucsd.edu/rentrac/
+URL: https://github.com/r3fang/crest
 
-usage: ${0##*/} [-h] [-i INPUT] [-r chr6:30132134-32138339] [-o PREFIX] [-m 5] [-s 50] [-c 3] [-p 0.05] [-l 1000] 
+usage: ${0##*/} [-h] [-i INPUT] [-t T1,T2,T3] [-c C1,C2,C3] [-r chr6:30132134-32138339] [-o PREFIX] [-m 5] [-s 50] [-n 3] [-p 0.05] [-l 1000] 
 
 Example:
-crest -i data/data.txt -r chr6:30132134-32138339 -o demo
+crest -i data/data.txt -t T1,T2,T3,T4,T5 -c C1,C2 -r chr6:30132134-32138339 -o demo
 
 Options: 
-	-h, --help                  show this help message and exit.
-	-i  INPUT                   input crest-standard matrix.
-	-r  INQUIRE_REGION          region that CREST-seq performed against.
-	-o  PREFIX                  prefix of outout file.
-	-m  MIN_CPM                 sgRNA pairs with CPM (count per million) smaller than
-	                            MIN_CPM will be filtered before analysis [5].
-	-s  BIN_SIZE                screened region INQUIRE_REGION will be partitioned into 
-	                            a set of BIN_SIZE-bp bins [50].
-	-c  MIN_COV                 a bin is considered significant at least MIN_COV pairs span it [2].
-	-p  FDRCUTOFF               FDR cutoff for a significant bin [0.05].
-	-l  MIN_WIDTH               a peak will be extended to MIN_WIDTH if shorter [1000].
+	-h, --help                show this help message and exit.
+	-i  INPUT                 input crest-standard matrix.
+	-t  TREAT                 treatment sample ID, seperated by comma without space.
+	-c  CONTROL               control sample ID, seperated by comma without space.
+	-r  REGION                region that CREST-seq performed against (e.g. chr6:1-100).
+	-o  PREFIX                prefix of outout files.
+	-m  MIN_CPM               sgRNA pairs with CPM (count per million) smaller than
+	                          MIN_CPM will be filtered before analysis [5].
+	-s  BIN_SIZE              screened region INQUIRE_REGION will be partitioned into 
+	                          a set of BIN_SIZE-bp bins [50].
+	-n  MIN_COV               a bin is considered significant at least MIN_COV pairs span it [2].
+	-p  FDRCUTOFF             FDR cutoff for a significant bin [0.05].
+	-l  MIN_WIDTH             a peak will be extended to MIN_WIDTH if shorter [1000].
 
 Note: To use crest, please be sure that the input matrix is in the required format.  
 EOF
@@ -46,25 +48,27 @@ MIN_WIDTH=1000
 MIN_COV=2
 
 # PART IV read in arguments
-while getopts ":i:r:o:m:s:c:p:l:" opt;
+while getopts ":i:t:c:r:o:m:s:n:p:l:" opt;
 do
 	case "$opt" in
 		i) INPUT=$OPTARG;;
+		t) TREAT_ID=$OPTARG;;
+		c) CONTROL_ID=$OPTARG;;
 		r) INQUIRE_REGION=$OPTARG;;
 		o) PREFIX=$OPTARG;;
 		m) MIN_CPM=$OPTARG;;
 		s) BIN_SIZE=$OPTARG;;
-		c) MIN_COV=$OPTARG;;
+		n) MIN_COV=$OPTARG;;
 		p) FDRCUTOFF=$OPTARG;;
 		l) MIN_WIDTH=$OPTARG;;
 		\?) usage
-			echo "input error"
+			echo "error: unrecoginized option -$OPTARG"
 			exit 1
 			;;
 	esac
 done
 
-if [ $# -lt 6 ] ; then
+if [ $# -lt 10 ] ; then
    usage
    echo "error: too few arguments"
    exit 1
@@ -78,6 +82,16 @@ fi
 if [ ! -f $INPUT ]; then
 	usage
     echo "error: input file -i '$INPUT' not exists.";
+	exit 1;
+fi
+
+if [ -z ${TREAT_ID+x} ]; then 
+	echo "error: missing variable -t TREAT_ID" >&2;
+	exit 1;
+fi
+
+if [ -z ${CONTROL_ID+x} ]; then 
+	echo "error: missing variable -c CONTROL_ID" >&2;
 	exit 1;
 fi
 
@@ -157,24 +171,30 @@ fi
 
 echo $0 $* 2>&1 | tee $PREFIX.log 
 echo 2>&1 | tee -a $PREFIX.log
-echo INPUT=$INPUT 2>&1 | tee -a $PREFIX.log
-echo INQUIRE_REGION=$INQUIRE_REGION 2>&1 | tee -a $PREFIX.log
-echo PREFIX=$PREFIX 2>&1 | tee -a $PREFIX.log
-echo BIN_SIZE=$BIN_SIZE 2>&1 | tee -a $PREFIX.log
-echo MIN_CPM=$MIN_CPM 2>&1 | tee -a $PREFIX.log
-echo FDRCUTOFF=$FDRCUTOFF 2>&1 | tee -a $PREFIX.log
+echo input file: $INPUT 2>&1 | tee -a $PREFIX.log
+echo treatment samples ID: $TREAT_ID 2>&1 | tee -a $PREFIX.log
+echo control samples ID: $CONTROL_ID 2>&1 | tee -a $PREFIX.log
+echo screened region: $INQUIRE_REGION 2>&1 | tee -a $PREFIX.log
+echo prefix of output file: $PREFIX 2>&1 | tee -a $PREFIX.log
+
+echo bin size: $BIN_SIZE 2>&1 | tee -a $PREFIX.log
+echo valid sgRNA pair min read count \(CPM\): $MIN_CPM 2>&1 | tee -a $PREFIX.log
+echo FDR cutoff: $FDRCUTOFF 2>&1 | tee -a $PREFIX.log
 echo 2>&1 | tee -a $PREFIX.log
 
 if [ -d $PREFIX\_tmp ]; then
 	rm -r $PREFIX\_tmp
 fi
 
-#mkdir $PREFIX\_tmp
+if [ ! -d $PREFIX\_tmp ]; then
+	mkdir $PREFIX\_tmp
+fi
+
 #crest_edger INQURE_REGION=\'$INQUIRE_REGION\' FIN_NAME=\'$INPUT\' GROUPS="c(2,2,2,2,2,1,1)" FOUT_NAME=\"$PREFIX\_tmp/$PREFIX.txt\" MIN_CPM=$MIN_CPM BIN_SIZE=$BIN_SIZE
 #RRA -i $PREFIX\_tmp/$PREFIX.txt -o $PREFIX\_tmp/$PREFIX.pvalue.txt -p 0.1 >/dev/null
 #crest_peak_call INPUT=\'$PREFIX\_tmp/$PREFIX.pvalue.txt\' PREFIX=\'$PREFIX\' MIN_COV=$MIN_COV MIN_WIDTH=$MIN_WIDTH FDR=$FDRCUTOFF
 #
-## cleanup
-#rm -r $PREFIX\_tmp
-#
+# cleanup
+# rm -r $PREFIX\_tmp
+
 
